#+Title: Etoile -- An emacs config using the straight package manager
#+Author: Jacob Salzberg

* Goals
The goals of this config are to
1. Use the straight package manager to manage packages,
   including cloning and building repositories.
   
2. Break up my emacs config into reusable parts
   
3. Be usable from any linux computer without hassle.
   

* Guidelines
1. Use use-package for every package loaded
2. Every package can be fetched from github (or another source defined by straight)
   that is to say, :straight should not be nil for any package except ones that are part of emacs.
3. If the configuration of a package takes more than ten lines, add an auxilary package
   called +[package_name] that contains the configuration
4. :defer when possible, :demand otherwise (but never leave that unspecified)

* Reminders
1. Edit ~/.emacs.d/straight/build/etoile/ and not the ~/.emacs.d/ itself!

* Installation:
Make sure you have no ~/.emacs file:
#+name: No .emacs
#+begin_src shell
mv ~/.emacs ~/.emacs.backup
#+end_src

Stow away your .emacs.d

#+name: No .emacs.d
#+begin_src shell
mv ~/.emacs.d ~/.emacs.d.old
#+end_src

Clone this repository

#+name: Clone etoile
#+begin_src shell
cd ~/
git clone https://github.com/jsalzbergedu/etoile-emacs.git
#+end_src


Finally, to install:
#+name: Install
#+begin_src shell
mkdir ~/.emacs.d
ln -s $HOME/etoile-emacs/init.el $HOME/.emacs.d/init.el
emacs
#+end_src
